### ISSUE TITLE
Issue with thorndike_seg1_solid sample for Thermal analysis

### ISSUE THREAD

**Issue by yvanblanchard** [linus131/DES_thermal_model#2]
Hello,

I tried to run the thermal analysis (with 'atomistic_thermal_analysis') of the sample "thorndike_seg1_solid.gcode", but calculations failed. I think I got a crash. Calculations are initiated, but it takes very long time (15 minutes), and I see that my 32 GB of RAM are fully reserved and consumed (so I guess that high computation time is caused by disk swapping..). And after it crashes.
I tried several times, and one time, I got the following message: "memory allocation of 40672800000 bytes failed".

**Comment by linus131** [comment]
Hi Yvan,
I think the computer runs out of memory. All the temperatures are stored in a vector and are only written to the disk at the end of the program. The model is large and has nearly 1 million elements. Multiply that with 180000 timesteps, and the memory requirements get too large.
A solution to this problem would be to write the results intermittently to the disk after a certain number of timesteps.
Best Regards,Sunil
    On Monday, October 17, 2022 at 03:59:46 AM EDT, Yvan Blanchard ***@***.***> wrote:  
 
 


Hello,

I tried to run the thermal analysis of the sample "thorndike_seg1_solid.gcode", but calculations failed. I think I got a crash. Calculations are initiated, but it takes very long time (15 minutes), and I see that my 32 GB of RAM are fully reserved and consumed (so I guess that high computation time is caused by disk swapping..). And after it crashes.
I tried several times, and one time, I got the following message: "memory allocation of 40672800000 bytes failed".
